name: Check Secret Value

on:
  push:
    branches:
      - master

jobs:
  validate_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate ATLETHES_SECRET secret variable
      run: |
        if [ -z "${{ secrets.ATLETHES_SECRET }}" ]; then
          echo "ATLETHES_SECRET no est치 configurado"
          exit 1
        else
          echo "ATLETHES_SECRET est치 configurado como: ${{ secrets.ATLETHES_SECRET }}"
        fi

    - name: Validate VAR_ACTIONS environment variable
      run: |
        if [ -z "${{ vars.VAR_ACTIONS }}" ]; then
          echo "VAR_ACTIONS no est치 configurada."
          exit 1
        else
          echo "VAR_ACTIONS est치 configurada como: ${{ vars.VAR_ACTIONS }}"
        fi
